# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messcut',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='messcut',
            name='end_date',
            field=models.DateField(),
        ),
    ]
