# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170420_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='messcut',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
